const state={centros:[],puestos:[],apariciones:[],recursos:[],dtPuestos:null,dtCentros:null,m:null};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],uniq=a=>[...new Set(a.filter(v=>v!==null&&v!==undefined&&v!==''))],byId=a=>Object.fromEntries(a.map(x=>[x.id,x]));
const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const latest=a=>[...a].sort((x,y)=>(y.anio||0)-(x.anio||0))[0];
const tags=a=>uniq(a).map(t=>`<span class="tag tag-${String(t).toLowerCase().replace(/[^a-z0-9]/g,'-')}">${esc(t)}</span>`).join(' ');
async function load(){const names=['centros','puestos','apariciones','recursos'];const rs=await Promise.all(names.map(n=>fetch(`data/${n}.json`,{cache:'no-store'})));rs.forEach((r,i)=>{if(!r.ok)throw new Error(`${names[i]}.json: ${r.status}`)});[state.centros,state.puestos,state.apariciones,state.recursos]=await Promise.all(rs.map(r=>r.json()));state.recursos.filter(r=>!state.centros.some(c=>c.id===r.centro)&&r.nombre).forEach(r=>state.centros.push({id:r.centro,nombre:r.nombre,provincia:r.provincia,localidad:r.localidad,tipo:r.tipo||'Centro',codigo:r.codigo||null}))}
function buildModels(){const cm=byId(state.centros),rm=Object.fromEntries(state.recursos.map(r=>[r.centro,r])),bp=new Map(),bc=new Map();state.apariciones.forEach(a=>{if(!bp.has(a.puesto))bp.set(a.puesto,[]);bp.get(a.puesto).push(a);if(a.centro){if(!bc.has(a.centro))bc.set(a.centro,[]);bc.get(a.centro).push(a)}});const cf=a=>a?.centro&&cm[a.centro]?cm[a.centro]:{id:null,nombre:'Centro pendiente de vincular',provincia:a?.provincia||'—',localidad:a?.localidad||'—',tipo:'Pendiente'};const centros=state.centros.map(c=>{const apps=bc.get(c.id)||[],recurso=rm[c.id]||null;return{...c,apps,recurso,puestos:uniq(apps.map(a=>a.puesto)).sort((a,b)=>a-b),fuentes:uniq(apps.map(a=>a.tipo)),last:latest(apps)}}).filter(c=>c.apps.length||c.recurso);return{cm,rm,cf,centros,puestos:state.puestos.map(p=>{const apps=bp.get(p.numero)||[],last=latest(apps),centro=cf(last);return{...p,apps,last,centro,recurso:centro.id?rm[centro.id]||null:null,fuentes:uniq(apps.map(a=>a.tipo))}})}}
function selected(){return{provincia:$('#filter-provincia').value,localidad:$('#filter-localidad').value,tipo:$('#filter-tipo-centro').value,recurso:$('#filter-recurso').value,fuente:$('#filter-fuente').value,anio:+$('#filter-anio').value||null}}
function geoPass(c,f){return(!f.provincia||c.provincia===f.provincia)&&(!f.localidad||c.localidad===f.localidad)&&(!f.tipo||c.tipo===f.tipo)}
function resourcePass(c,f){const r=c.recurso?.recurso||'';return !f.recurso||(f.recurso==='SIN_CONFIRMAR'?!r:r===f.recurso)}
function appPass(a,f,m){const c=m.cf(a),model=c.id?m.centros.find(x=>x.id===c.id):{...c,recurso:null};return geoPass(c,f)&&resourcePass(model||{recurso:null},f)&&(!f.fuente||a.tipo===f.fuente)&&(!f.anio||(a.anio||0)>=f.anio)}
function centrePass(c,f){if(!geoPass(c,f)||!resourcePass(c,f))return false;if(f.fuente||f.anio)return c.apps.some(a=>(!f.fuente||a.tipo===f.fuente)&&(!f.anio||(a.anio||0)>=f.anio));return true}
function fill(sel,vals){const el=$(sel);vals.forEach(v=>el.insertAdjacentHTML('beforeend',`<option value="${esc(v)}">${esc(v)}</option>`))}
function lang(){return{search:'Buscar:',lengthMenu:'Mostrar _MENU_',info:'_START_–_END_ de _TOTAL_',infoEmpty:'Sin resultados',zeroRecords:'No hay coincidencias',emptyTable:'No hay datos',paginate:{next:'›',previous:'‹'}}}
function resourceBadge(r){return r?tags([r.recurso]):'<span class="muted">—</span>'}
function renderRows(){const m=state.m,tp=$('#tabla-puestos tbody'),tc=$('#tabla-centros tbody');tp.innerHTML='';tc.innerHTML='';m.puestos.forEach(p=>{const c=p.centro,l=p.last,tr=document.createElement('tr');tr.dataset.puesto=p.numero;tr.innerHTML=`<td data-order="${p.numero}"><span class="number-chip">${p.numero}</span></td><td>${esc(c.provincia)}</td><td>${c.id?`<button class="text-link centre-btn" data-centro="${esc(c.id)}">${esc(c.nombre)}</button>`:esc(c.nombre)}</td><td>${esc(c.localidad)}</td><td>${resourceBadge(p.recurso)}</td><td>${tags(p.fuentes)}</td><td data-order="${l?.anio||0}">${l?`${l.anio} · ${esc(l.referencia)}`:'—'}</td><td>${p.apps.length}</td><td><button class="button button-link history-btn" data-puesto="${p.numero}">Historial</button></td>`;tp.appendChild(tr)});m.centros.forEach(c=>{const tr=document.createElement('tr');tr.dataset.centro=c.id;tr.innerHTML=`<td>${esc(c.provincia)}</td><td>${esc(c.localidad)}</td><td><button class="text-link centre-btn" data-centro="${esc(c.id)}"><strong>${esc(c.nombre)}</strong></button></td><td>${esc(c.tipo)}</td><td>${resourceBadge(c.recurso)}</td><td>${esc(c.codigo||'—')}</td><td data-order="${c.puestos.length}">${c.puestos.length?c.puestos.join(', '):'—'}</td><td data-order="${c.last?.anio||0}">${c.last?`${c.last.anio} · ${esc(c.last.referencia)}`:'Sin histórico'}</td>`;tc.appendChild(tr)})}
function initFilters(){fill('#filter-provincia',uniq(state.m.centros.map(c=>c.provincia).concat(state.apariciones.map(a=>a.provincia))).sort());fill('#filter-localidad',uniq(state.m.centros.map(c=>c.localidad).concat(state.apariciones.map(a=>a.localidad))).sort());fill('#filter-tipo-centro',uniq(state.m.centros.map(c=>c.tipo)).sort());fill('#filter-anio',uniq(state.apariciones.map(a=>a.anio)).sort((a,b)=>b-a));['#filter-provincia','#filter-localidad','#filter-tipo-centro','#filter-recurso','#filter-fuente','#filter-anio'].forEach(s=>$(s).addEventListener('change',refresh));$('#clear-filters').onclick=()=>{['#filter-provincia','#filter-localidad','#filter-tipo-centro','#filter-recurso','#filter-fuente','#filter-anio'].forEach(s=>$(s).value='');refresh()}}
function filtered(){const f=selected(),m=state.m;return{apps:state.apariciones.filter(a=>appPass(a,f,m)),centros:m.centros.filter(c=>centrePass(c,f)),puestos:m.puestos.filter(p=>p.apps.some(a=>appPass(a,f,m)))}}
function installDataTables(){if(typeof DataTable==='undefined')return;DataTable.ext.search.push((settings,data,index)=>{const f=selected(),m=state.m,row=settings.aoData?.[index]?.nTr;if(settings.nTable.id==='tabla-puestos'){const p=m.puestos.find(x=>x.numero===+(row?.dataset?.puesto||0));return !p||p.apps.some(a=>appPass(a,f,m))}if(settings.nTable.id==='tabla-centros'){const c=m.centros.find(x=>x.id===row?.dataset?.centro);return !c||centrePass(c,f)}return true});state.dtPuestos=new DataTable('#tabla-puestos',{pageLength:25,order:[[0,'asc']],language:lang(),columnDefs:[{targets:8,orderable:false,searchable:false}]});state.dtCentros=new DataTable('#tabla-centros',{pageLength:25,order:[[0,'asc'],[1,'asc'],[2,'asc']],language:lang()})}
function manualFilter(){const f=selected(),m=state.m;$$('#tabla-puestos tbody tr').forEach(tr=>{const p=m.puestos.find(x=>x.numero===+tr.dataset.puesto);tr.hidden=!!p&&!p.apps.some(a=>appPass(a,f,m))});$$('#tabla-centros tbody tr').forEach(tr=>{const c=m.centros.find(x=>x.id===tr.dataset.centro);tr.hidden=!!c&&!centrePass(c,f)})}
function refresh(){const x=filtered();$('#stat-puestos').textContent=x.puestos.length;$('#stat-centros').textContent=x.centros.length;$('#stat-localidades').textContent=uniq(x.centros.map(c=>`${c.provincia}|${c.localidad}`)).length;$('#stat-apariciones').textContent=x.apps.length;renderLocations(x.centros);if(state.dtPuestos&&state.dtCentros){state.dtPuestos.draw(false);state.dtCentros.draw(false)}else manualFilter()}
function renderLocations(centros){const root=$('#localidades-list'),tree={};root.innerHTML='';centros.forEach(c=>{tree[c.provincia]??={};tree[c.provincia][c.localidad]??=[];tree[c.provincia][c.localidad].push(c)});Object.keys(tree).sort().forEach(p=>{const b=document.createElement('div');b.className='province-block';b.innerHTML=`<h3>${esc(p)}</h3>`;Object.keys(tree[p]).sort().forEach(l=>{const cs=tree[p][l],d=document.createElement('details'),np=uniq(cs.flatMap(c=>c.puestos));d.className='location-card';d.innerHTML=`<summary><span class="location-name">${esc(l)}</span><span class="location-meta">${cs.length} centros · ${np.length} puestos conocidos</span></summary><div class="centres-inside">${cs.sort((a,b)=>a.nombre.localeCompare(b.nombre)).map(c=>`<button class="centre-row centre-btn" data-centro="${esc(c.id)}"><span><strong>${esc(c.nombre)}</strong><small>${esc(c.tipo)} ${c.codigo?`· ${esc(c.codigo)}`:''}</small></span><span class="centre-row-right">${resourceBadge(c.recurso)}<span class="puestos-inline">${c.puestos.length?c.puestos.join(' · '):'Sin puesto C1 vinculado'}</span><span class="open-label">Ver ficha →</span></span></button>`).join('')}</div>`;b.appendChild(d)});root.appendChild(b)});if(!root.children.length)root.innerHTML='<p class="muted">No hay centros que coincidan con los filtros.</p>'}
function openHistory(n){const m=state.m,p=m.puestos.find(x=>x.numero===+n);if(!p)return;$('#history-title').textContent=`Puesto ${p.numero}`;$('#history-content').innerHTML=[...p.apps].sort((a,b)=>(b.anio||0)-(a.anio||0)).map(a=>{const c=m.cf(a),admin=a.centro_administrativo&&m.cm[a.centro_administrativo];return`<article class="history-item"><div class="history-top"><h3>${a.anio} · ${esc(a.referencia)}</h3>${tags([a.tipo])}</div><p>${c.id?`<button class="text-link centre-btn" data-centro="${esc(c.id)}"><strong>${esc(c.nombre)}</strong></button>`:`<strong>${esc(c.nombre)}</strong>`} · ${esc(c.localidad)}, ${esc(c.provincia)}</p>${admin?`<p>Centro administrativo: ${esc(admin.nombre)}</p>`:''}${a.nota?`<p>${esc(a.nota)}</p>`:''}${a.url?`<p><a class="source-link" href="${esc(a.url)}" target="_blank" rel="noopener">Abrir fuente oficial ↗</a></p>`:''}</article>`}).join('');$('#history-dialog').showModal()}
function activityLabel(c){const adc=c.apps.filter(a=>a.tipo==='ADC').length;if(adc>=5)return'Muy recurrente';if(adc>=3)return'Recurrente';if(adc>=1)return'Ocasional';return'Sin ADC conocido'}
function openCentre(id){const m=state.m,c=m.centros.find(x=>x.id===id);if(!c)return;const apps=[...c.apps].sort((a,b)=>(b.anio||0)-(a.anio||0)),r=c.recurso,last=latest(apps);$('#centre-title').textContent=c.nombre;$('#centre-subtitle').textContent=`${c.localidad} · ${c.provincia} · ${c.tipo}${c.codigo?` · código ${c.codigo}`:''}`;const resourceHtml=r?`<section class="centre-section resource-card"><p class="eyebrow">Recurso oficial confirmado</p><h3>${esc(r.recurso)} ${r.titularidad?`· ${esc(r.titularidad)}`:''}</h3>${r.unidades_autorizadas?`<p><strong>${r.unidades_autorizadas}</strong> unidad de Educación Especial autorizada · <strong>${r.puestos_escolares_autorizados||'—'}</strong> puestos escolares autorizados.</p>`:''}<p class="muted">Fuente: ${esc(r.fuente)}${r.curso?` · ${esc(r.curso)}`:''}</p>${r.url?`<a class="source-link" target="_blank" rel="noopener" href="${esc(r.url)}">Abrir fuente oficial ↗</a>`:''}</section>`:'';$('#centre-content').innerHTML=`<div class="centre-summary"><div><span>Puestos C1 conocidos</span><strong>${c.puestos.length}</strong></div><div><span>ADC documentados</span><strong>${apps.filter(a=>a.tipo==='ADC').length}</strong></div><div><span>Actividad histórica</span><strong>${activityLabel(c)}</strong></div><div><span>Última aparición</span><strong>${last?last.anio:'—'}</strong></div></div>${resourceHtml}<section class="centre-section"><p class="eyebrow">Números de puesto documentados</p><div class="number-grid">${c.puestos.length?c.puestos.map(n=>`<button class="number-card history-btn" data-puesto="${n}"><span>${n}</span><small>Ver historial</small></button>`).join(''):'<p class="muted">Aún no hay un número C1-04-03 vinculado en el histórico recopilado.</p>'}</div><p class="muted">Este recuento no debe interpretarse todavía como plantilla actual del centro.</p></section><section class="centre-section"><p class="eyebrow">Histórico documentado</p><div class="timeline">${apps.length?apps.map(a=>`<article class="timeline-row"><div><strong>${a.anio}</strong><span>${esc(a.referencia)}</span></div><div><span class="number-chip">${a.puesto}</span> ${tags([a.tipo])}${a.nota?`<p>${esc(a.nota)}</p>`:''}</div></article>`).join(''):'<p class="muted">Sin apariciones ADC/RPT cargadas todavía.</p>'}</div></section>`;$('#centre-dialog').showModal()}
function bind(){document.addEventListener('click',e=>{const h=e.target.closest('.history-btn');if(h){$('#centre-dialog')?.open&&$('#centre-dialog').close();openHistory(h.dataset.puesto);return}const c=e.target.closest('.centre-btn');if(c){$('#history-dialog')?.open&&$('#history-dialog').close();openCentre(c.dataset.centro);return}const x=e.target.closest('[data-close]');if(x)document.getElementById(x.dataset.close)?.close()});$$('.nav-tab:not(:disabled)').forEach(b=>b.onclick=()=>{$$('.nav-tab').forEach(x=>x.classList.remove('is-active'));b.classList.add('is-active');$$('.view').forEach(v=>v.classList.remove('is-active'));$(`#view-${b.dataset.view}`).classList.add('is-active');setTimeout(()=>{state.dtPuestos?.columns?.adjust?.();state.dtCentros?.columns?.adjust?.()},0)});$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close()}))}
(async()=>{const status=$('#app-status');try{await load();state.m=buildModels();renderRows();initFilters();bind();refresh();try{installDataTables();refresh()}catch(e){console.warn('DataTables no disponible; se usa la tabla básica.',e)}}catch(e){console.error(e);status.hidden=false;status.className='app-status is-error';status.textContent='No se pudieron cargar los datos. Prueba a recargar la página.'}})();